### PR TITLE
fix(chat): Fix the run_command tool on Windows (#2179)

### LINKED ISSUE #2179: [Bug]: Issues with cmd_runner on Windows when quoted strings are provided
### Pre-submission checklist

- [x] I have read the [documentation](https://codecompanion.olimorris.dev)
- [x] I have updated the plugin and all dependencies to the latest versions
- [x] I have searched for existing [issues](https://github.com/olimorris/codecompanion.nvim/issues) and [discussions](https://github.com/olimorris/codecompanion.nvim/discussions)
- [x] My issue is not a minor or cosmetic quirk (e.g., formatting, spacing, or other non-functional details)

### Neovim version (nvim -v)

0.11.4

### Operating system/version

Windows 11

### Adapter and model

Copilot and claude-sonnet-4

### Describe the bug

I have run into situations where Claude 4 wants to execute `grep -n "expression" "c:\source\full\path.cpp"` with quotes and all. It failed to find the file. I eventually wrangled it to run a grep program I wrote to see what parameters it was receiving, and they included the literal quote (`"`) characters.

I have tracked it down to `lua\codecompanion\tools\utils\tools.lua` method `build_shell_command` which doesn't use Neovim's complicated way to build a shell command line.

I'm guessing cmd.exe only performs `"` stripping when invoked with a single long command line instead of a more POSIX like argv. I may be wrong. But...

I have patched that file locally to use `powershell.exe` and `-C` instead of `cmd.exe` and `/c`, so something like:

```lua
function M.build_shell_command(args)
  return {
    (vim.fn.has("win32") == 1 and "powershell" or "sh"),
    vim.fn.has("win32") == 1 and "-C" or "-c",
    table.concat(args, " "),
  }
end
```

With this change... it now runs!

Technically, using `vim.fn.cmd("!" .. table.concat(args, " "))` would be better *in terms of* how Neovim invokes the shell, but I'm guessing there is a reason why the code was written in terms of `vim.system`?

### Steps to reproduce

I've managed to consistently get the AI to execute an exact grep command by telling it something like this:

```
## Me

> Context:
> - <group>full_stack_dev</group>

@{full_stack_dev}

Execute the shell command `findstr "echo" "c:\a\test.txt"`

## CodeCompanion (Copilot)

I'll execute the shell command for you.

`findstr "echo" "c:\a\test.txt"` error
``txt
FINDSTR: Cannot open "c:\a\test.txt"
``
```

`c:\a\test.txt` is:

```
echo
no
```

Without 

### Expected behavior

With the above setup + the patch to tools.lua to use powershell -C instead of cmd.exe /c:

```
## Me

> Context:
> - <group>full_stack_dev</group>

@{full_stack_dev}

Execute the shell command `findstr "echo" "c:\a\test.txt"`

## CodeCompanion (Copilot)

I'll execute the shell command `findstr "echo" "c:\a\test.txt"` for you.

`findstr "echo" "c:\a\test.txt"`
``
echo
``


The command executed successfully and found one line in the file `c:\a\test.txt` that contains the word "echo". The output shows that there is a line containing just "echo" in that file.

Would you like me to run any additional commands or help you with something else related to this file?
```

I would expect anything other than "couldn't find `"` c:\a\test.txt `"`"

### Screenshots or recordings (optional)

_No response_

### minimal.lua file

```lua
-- I'm not sure how entirely relevant this is, as it can be observed with:
-- :lua vim.system({"cmd.exe", "/c", 'findstr "echo" "c:\a\test.txt"'}, {}, function(out) print(out.stderr) end)
-- vs
-- :lua vim.system({"powershell", "-C", 'findstr "echo" "c:\a\test.txt"'}, {}, function(out) print(out.stdout) end)
--

---@diagnostic disable: missing-fields

--[[
NOTE: Set the config path to enable the copilot adapter to work.
It will search the following paths for a token:
  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
--]]
vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      -- needed to install additional parsers
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
      { "nvim-lua/plenary.nvim" },
      -- Test with blink.cmp (delete if not required)
      {
        "saghen/blink.cmp",
        lazy = false,
        version = "*",
        opts = {
          keymap = {
            preset = "enter",
            ["<S-Tab>"] = { "select_prev", "fallback" },
            ["<Tab>"] = { "select_next", "fallback" },
          },
          cmdline = { sources = { "cmdline" } },
          sources = {
            default = { "lsp", "path", "buffer", "codecompanion" },
          },
        },
      },
      -- Test with nvim-cmp
      -- { "hrsh7th/nvim-cmp" },
    },
    opts = {
      --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      strategies = {
        --NOTE: Change the adapter as required
        chat = { adapter = "copilot" },
        inline = { adapter = "copilot" },
      },
      opts = {
        log_level = "DEBUG",
      },
    },
  },
  {
    "github/copilot.vim",
  }
}


require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
  treesitter.setup({
    ensure_installed = { "lua", "markdown", "markdown_inline", "yaml", "diff" },
    highlight = { enable = true },
  })
end

-- Setup nvim-cmp
-- local cmp_status, cmp = pcall(require, "cmp")
-- if cmp_status then
--   cmp.setup({
--     mapping = cmp.mapping.preset.insert({
--       ["<C-b>"] = cmp.mapping.scroll_docs(-4),
--       ["<C-f>"] = cmp.mapping.scroll_docs(4),
--       ["<C-Space>"] = cmp.mapping.complete(),
--       ["<C-e>"] = cmp.mapping.abort(),
--       ["<CR>"] = cmp.mapping.confirm({ select = true }),
--       -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
--     }),
--   })
-- end
```

### Log output (optional)

_No response_

### Minimal reproduction confirmation

- [x] Yes, I have tested and provided a `minimal.lua` file that reproduces the issue

### PR DESCRIPTION
**Pull request by alzwded**
## Description

Parameter quoting rules on Windows are complicated, because Windows programs only receive one big string with all arguments which they or msvcrt split back into argv. libuv used by NeoVim tries to be helpful, but ends up sending literal quotes to cmd.exe (programs get `"C:\file.txt"` with quotes instead of `C:\file.txt`) or not literal enough to powershell (literal empty arguments `""` get lost along the way)

For those who don't doze on their wind: https://web.archive.org/web/20190109172835/https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

Creating a temporary .bat file and executing it _almost_ works, but I have had the LLM propose running `for ... %i ...` commands which require doubling up the percentage sign. Even with prompting, it would still occasionally throw a `FOR` curveball.

What does work, is typing the command INTO cmd.exe, and letting cmd.exe figure things out. So we send table.concat(cmd, " ") on stdin, and run cmd.exe. But... we need a couple of things set up so as to not confuse the the LLM:
* pass /K to inhibit the Microsoft Logo and copyright; it will exit when stdin is exhausted
* pass /Q to inhibit showing the command we're executing, since that's not part of the output
* set %PROMPT% to a space, so that it doesn't see any c:\> prompt; %PROMPT% == "" means "use the default", hence one space
* tac a "\n" at the end of the command, since cmd doesn't treat EOF as an implicit CR, and it would just print out `More?` like a silly goose.

This seems to have resolved all the issues I was encountering.

I've added a windows-only test which invokes the `find` command (no relation to POSIX `find`), which is one of the more troublesome commands. 

## Related Issue(s)

- Fixes #2179 

## Screenshots

N/A

## Checklist

- [x] I've read the [contributing](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [x] I've added [test](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md#testing) coverage for this fix/feature
- [x] I've run `make all` to ensure docs are generated, tests pass and my formatting is applied
- [ ] _(optional)_ I've updated `CodeCompanion.has` in the [init.lua](https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/init.lua#L239) file for my new feature
- [ ] _(optional)_ I've updated the README and/or relevant docs pages

### CODE REVIEW

**Comment by alzwded** [comment]
Mmm... actually, tests seem to be failing, either because they now get an extra `^M`, or, even more strangely, in WSL they get a full PROMPT in the output. Argh...

File: lua/codecompanion/strategies/chat/tools/orchestrator.lua [hunk 1]
```diff
@@ -69,7 +69,46 @@ local function cmd_to_func_tool(tool)
                 data = combined,
               })
             end
-          end)
+          end
+
+          if vim.fn.has("win32") then
+            -- Parameter quoting rules on Windows are complicated, because
```
Comment (olimorris) [inline lua/codecompanion/strategies/chat/tools/orchestrator.lua]: Let's remove this comment block and just reference this PR number

File: lua/codecompanion/strategies/chat/tools/orchestrator.lua [hunk 2]
```diff
@@ -37,7 +37,7 @@ local function cmd_to_func_tool(tool)
         ---@param tools CodeCompanion.Tools
         return function(tools, _, _, cb)
           cb = vim.schedule_wrap(cb)
-          vim.system(tool_utils.build_shell_command(cmd), {}, function(out)
+          local out_cb = function(out)
```
Comment (olimorris) [inline lua/codecompanion/strategies/chat/tools/orchestrator.lua]: Can we rename these? `out_cb` and `out` don't mean anything to me. In the context of a command being executed for the user, it could mean "out" as in "output" or "out" as in "stdout".

**Comment by olimorris** [comment]
Firstly, thanks so much for adding test coverage. Really, really appreciate that.

Few minor points but this looks great.

**Comment by alzwded** [comment]
> Firstly, thanks so much for adding test coverage. Really, really appreciate that.
> 
> Few minor points but this looks great.

No probs. I'll sort out the comments. I'm wondering if that test needs to be in a different suite?

I actually see test failures in very strange ways (I see CI also failed here) on test_cmd in particular. Like... when running in WSL, it somehow ends up calling cmd.exe, even though when I run nvim in there it `has('win32')` reports false. This is going to take a while....

File: lua/codecompanion/strategies/chat/tools/orchestrator.lua (hunk 1 above)
Comment (alzwded) [reply lua/codecompanion/strategies/chat/tools/orchestrator.lua]: Done

File: lua/codecompanion/strategies/chat/tools/orchestrator.lua (hunk 2 above)
Comment (alzwded) [reply lua/codecompanion/strategies/chat/tools/orchestrator.lua]: Yes. Referencing `:help vim.system`, I've renamed `out_cb` to `system_on_exit_cb`, `out` to `process_result_obj` (the docs' example just call it obj), and `pattern` to `split_pattern`.

**Comment by alzwded** [comment]
> > Firstly, thanks so much for adding test coverage. Really, really appreciate that.
> > Few minor points but this looks great.
> 
> No probs. I'll sort out the comments. I'm wondering if that test needs to be in a different suite?
> 
> I actually see test failures in very strange ways (I see CI also failed here) on test_cmd in particular. Like... when running in WSL, it somehow ends up calling cmd.exe, even though when I run nvim in there it `has('win32')` reports false. This is going to take a while....

@olimorris okay, I'm pretty sure nothing is broken now, and I am happy with the state of the PR. All tests pass on my Ubuntu.

On Windows, most tests pass, except a handful which try to execute some non-Windows native shell commands (`sleep`), or they try to load `python.so` which is not a Windows binary.

I have a 3rd commit 0ba4a4f25f8a0b8c9f1ea0c1e9342402245b094f added to the bunch which increases the timeouts in `test_cmd.lua`. It might just be my machine is slow, but Windows generally takes its merry time to spawn processes (getting more than 1 process spawned per second is a miracle in Windows land). Let me know if you'd like me to drop that commit from this PR.

File: tests/strategies/chat/tools/runtime/test_cmd.lua
Comment (olimorris) [inline tests/strategies/chat/tools/runtime/test_cmd.lua:1]: I'd really like to not increase these waits. They take long enough to run on my machine as it is. If this is a Windows fix, then let's detect it and adjust the waits up front.

**Comment by olimorris** [comment]
Awesome. Just a minor fix regarding the wait times then I'll be happy to merge this. Thanks.

File: tests/strategies/chat/tools/runtime/test_cmd.lua
Comment (alzwded) [reply tests/strategies/chat/tools/runtime/test_cmd.lua:1]: Tell you what -- I've left out that commit. I'm thinking of doing [a different PR](https://github.com/alzwded/codecompanion.nvim/tree/make-tests-run-on-native-windows) to make tests run on native Windows, as a whole. I'll keep what you said in mind and if timeouts need to be adjusted for Windows only, it will be for windows only. "Fixing" tests on native Windows isn't strictly related to my Bug report...

**Comment by alzwded** [comment]
> Awesome. Just a minor fix regarding the wait times then I'll be happy to merge this. Thanks.

popped off the commit which change the timeouts in test_cmd, and created #2200 which makes tests work on Windows in general.

**Comment by olimorris** [comment]
@alzwded - I've split out the shell execution into its own func. Tests pass my end. Can you check they're good for you?

**Comment by alzwded** [comment]
> @alzwded - I've split out the shell execution into its own func. Tests pass my end. Can you check they're good for you?

@olimorris I've checked again, and in the callback you pass to execute shell command, it's rather important to use `"\r?\n"` on Windows, since lines tend to be terminated by `\r\n` (unless some file or some program refuses to throw in ASCII 13 in there; which is why I set it to _LF maybe preceded by CR_).

I've added a commit to add the difference in EOL pattern on Windows.

**Comment by alzwded** [comment]
> > @alzwded - I've split out the shell execution into its own func. Tests pass my end. Can you check they're good for you?
> 
> @olimorris I've checked again, and in the callback you pass to execute shell command, it's rather important to use `"\r?\n"` on Windows, since lines tend to be terminated by `\r\n` (unless some file or some program refuses to throw in ASCII 13 in there; which is why I set it to _LF maybe preceded by CR_).
> 
> I've added a commit to add the difference in EOL pattern on Windows.

For context, without my `"\r?\n"` commit, this happens:

<details>
<summary>Failing tests</summary>

```
FAIL in tests\strategies\chat\tools\catalog\test_cmd_runner.lua | cmd_runner tool:
  Failed expectation for screenshot equality to reference at "tests/screenshots/tests-strategies-chat-tools-catalog-test_cmd_runner.lua---cmd_runner-tool".
  Different `text` cell at line 9 column 1. Reference: "h". Observed: "^".
  Reference:
  --|---------|---------|---------|---------|---------|---------|---------|---------|
  01|## foo                              â",
  02|                                    â",~
  03|                                    â",~
  04|                                    â",~
  05|## assistant                        â",~
  06|                                    â",~
  07|`echo hello world`                  â",~
  08|```                                 â",~
  09|hello world                         â",~
  10|```                                 â",~
  11|                                    â",~
  12|## foo                              â",~
  13|                                    â",~
  14|                                    â",~
  15|~                                   â",~
  16|~                                   â",~
  17|~                                   â",~
  18|~                                   â",~
  19|~                                   â",~
  20|~                                   â",~
  21|~                                   â",~
  22|~                                   â",~
  23|~                                   â",~
  24|~                                   â",~

  --|---------|---------|---------|---------|---------|---------|---------|---------|
  01|00000011111111111111111111111111111121111111111111111111111111111111111111111111
  02|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  03|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  04|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  05|00000000000011111111111111111111111123333333333333333333333333333333333333333333
  06|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  07|44444444444444444411111111111111111123333333333333333333333333333333333333333333
  08|44411111111111111111111111111111111123333333333333333333333333333333333333333333
  09|44444444444111111111111111111111111123333333333333333333333333333333333333333333
  10|44411111111111111111111111111111111123333333333333333333333333333333333333333333
  11|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  12|00000011111111111111111111111111111123333333333333333333333333333333333333333333
  13|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  14|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  15|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  16|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  17|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  18|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  19|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  20|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  21|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  22|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  23|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  24|33333333333333333333333333333333333323333333333333333333333333333333333333333333

  Observed:
  --|---------|---------|---------|---------|---------|---------|---------|---------|
  01|## foo                              â",
  02|                                    â",~
  03|                                    â",~
  04|                                    â",~
  05|## assistant                        â",~
  06|                                    â",~
  07|`echo hello world`                  â",~
  08|```                                 â",~
  09|^M                                  â",~
  10|hello world^M                       â",~
  11|^M                                  â",~
  12|^M                                  â",~
  13|```                                 â",~
  14|                                    â",~
  15|## foo                              â",~
  16|                                    â",~
  17|                                    â",~
  18|~                                   â",~
  19|~                                   â",~
  20|~                                   â",~
  21|~                                   â",~
  22|~                                   â",~
  23|~                                   â",~
  24|~                                   â",~

  --|---------|---------|---------|---------|---------|---------|---------|---------|
  01|00000011111111111111111111111111111121111111111111111111111111111111111111111111
  02|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  03|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  04|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  05|00000000000011111111111111111111111123333333333333333333333333333333333333333333
  06|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  07|44444444444444444411111111111111111123333333333333333333333333333333333333333333
  08|44411111111111111111111111111111111123333333333333333333333333333333333333333333
  09|55111111111111111111111111111111111123333333333333333333333333333333333333333333
  10|44444444444551111111111111111111111123333333333333333333333333333333333333333333
  11|55111111111111111111111111111111111123333333333333333333333333333333333333333333
  12|55111111111111111111111111111111111123333333333333333333333333333333333333333333
  13|44411111111111111111111111111111111123333333333333333333333333333333333333333333
  14|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  15|00000011111111111111111111111111111123333333333333333333333333333333333333333333
  16|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  17|11111111111111111111111111111111111123333333333333333333333333333333333333333333
  18|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  19|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  20|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  21|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  22|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  23|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  24|33333333333333333333333333333333333323333333333333333333333333333333333333333333
  Traceback:
    tests\strategies\chat\tools\catalog\test_cmd_runner.lua:40

FAIL in tests\strategies\chat\tools\runtime\test_cmd.lua | Tools | cmds | handlers and outputs are called:
  Failed expectation for equality.
  Left:  "Hello World"
  Right: "\r"
  Traceback:
    tests\strategies\chat\tools\runtime\test_cmd.lua:56

FAIL in tests\strategies\chat\tools\runtime\test_cmd.lua | Tools | cmds | can run multiple commands:
  Failed expectation for equality.
  Left:  { "Hello World" }
  Right: { "\r", "Hello World\r", "\r", "\r" }
  Traceback:
    tests\strategies\chat\tools\runtime\test_cmd.lua:107


```

</details>

With the `\r?\n` thing, those tests pass, since the `\r`s get stripped together with the `\n`.

I didn't notice the LLM getting confused by stray CRs, but it's probably better to keep things consistent across platforms.
