### PR TITLE
fix(tools): builtin tools do not pass rejection reasons back to LLM (#2916)

### LINKED ISSUE #2916: [Bug]: User rejection reason not passed to LLM
### Pre-submission checklist

- [x] I have read the [documentation](https://codecompanion.olimorris.dev)
- [x] I have updated the plugin and all dependencies to the latest versions
- [x] I have searched for existing [issues](https://github.com/olimorris/codecompanion.nvim/issues) and [discussions](https://github.com/olimorris/codecompanion.nvim/discussions)
- [x] My issue is not a minor or cosmetic quirk (e.g., formatting, spacing, or other non-functional details)

### Neovim version (nvim -v)

NVIM v0.12.0-dev-2664+g256811a617

### Operating system/version

Linux

### Adapter and model

Any

### Describe the bug

When a user rejects a tool execution with a reason, the reason is not correctly passed back to the LLM. The [`helpers.rejected`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua#L10) function checks for `opts.reason`, but the orchestrator passes the reason in `opts.opts.reason`.

**Root cause:**

In [`orchestrator.lua:211`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/orchestrator.lua#L211), when calling the tool's `rejected` handler:

```lua
self.tool.output.rejected(self.tool, { cmd = cmd, tools = self.tools, opts = opts })
```

The `opts` table contains `reason`, but it's nested inside the `opts` field of the passed table. So the structure is:

```lua
{ cmd = cmd, tools = self.tools, opts = { reason = "user's reason" } }
```

However, [`helpers.rejected`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua#L10) checks:

```lua
if opts.reason then  -- This is nil, should be opts.opts.reason
  rejection = fmt('%s, with the reason: "%s"', rejection, opts.reason)
end
```

### Affected tools

| Tool | File |
|------|------|
| `grep_search` | [`grep_search.lua:271`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/grep_search.lua#L271) |
| `file_search` | [`file_search.lua:175`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/file_search.lua#L175) |
| `read_file` | [`read_file.lua:218`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/read_file.lua#L218) |
| `create_file` | [`create_file.lua:197`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/create_file.lua#L197) |
| `delete_file` | [`delete_file.lua:135`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/delete_file.lua#L135) |
| `run_command` | [`run_command.lua:69`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/run_command.lua#L69) |
| `cmd_tool` (factory) | [`cmd_tool.lua:87`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/cmd_tool.lua#L87) |
| `get_diagnostics` | [`get_diagnostics.lua:220`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/get_diagnostics.lua#L220) |
| `get_changed_files` | [`get_changed_files.lua:166`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/get_changed_files.lua#L166) |
| `memory` | [`memory.lua:576`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/memory.lua#L576) |

### Suggested fix

Modify [`helpers/init.lua`](https://github.com/olimorris/codecompanion.nvim/blob/d5551b1aac60e164fb569eba422ea9b65cd2d6f4/lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua#L10):

```lua
M.rejected = function(self, opts)
  opts = opts or {}

  local rejection = opts.message or "The user declined to execute the tool"
  -- Fix: check opts.opts.reason first, fallback to opts.reason for backward compatibility
  local reason = opts.opts and opts.opts.reason or opts.reason
  if reason then
    rejection = fmt('%s, with the reason: "%s"', rejection, reason)
  end

  return opts.tools.chat:add_tool_output(self, rejection)
end
```

### Steps to reproduce

1. Open Neovim with the provided minimal.lua
2. Start a chat and trigger any tool that requires approval (e.g., `read_file`, `create_file`, `run_command`)
3. When prompted for approval, select "Reject"
4. Enter a reason for rejection when prompted
5. Press `gd` to open debug window and observe that the LLM receives "The user rejected the [tool] tool" without the reason

### Expected behavior

When a user provides a rejection reason, it should be included in the message sent back to the LLM:

```
The user rejected the [tool] tool, with the reason: "[user's reason]"
```

### Screenshots or recordings (optional)

_No response_

### minimal.lua file

```lua
Use the repository's existing [`minimal.lua`](https://github.com/olimorris/codecompanion.nvim/blob/main/minimal.lua) directly. No modifications needed as this is a code logic bug, not configuration-dependent.
```

### Log output (optional)

_No response_

### Minimal reproduction confirmation

- [x] Yes, I have tested and provided a `minimal.lua` file that reproduces the issue

### PR DESCRIPTION
**Pull request by cairijun**
## Description
* Fix builtin tool helper to use the correct rejection reason field
* Add `LC_ALL=C` to `Makefile` to ensure preditable screenshots, otherwise several tests might fail for developers with non-C/en locale

## AI Usage
CC + GLM5

The original issue was investigated and written by AI. This PR was also made by AI, following my instructions on where and how to test the fix.

## Related Issue(s)
Fix #2916

## Screenshots
image

## Checklist

- [x] I've read the [contributing](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [x] I confirm that this PR has been majority created by me, and not AI (unless stated in the "AI Usage" section above)
- [x] I've run `make all` to ensure docs are generated, tests pass and [StyLua](https://github.com/JohnnyMorganz/StyLua) has formatted the code
- [x] _(optional)_ I've added [test](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md#testing) coverage for this fix/feature
- [ ] _(optional)_ I've updated the README and/or relevant docs pages

### CODE REVIEW

File: lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua [hunk 1]
```diff
@@ -4,17 +4,17 @@ local M = {}
 
 ---Rejection message back to the LLM
 ---@param self CodeCompanion.Tools.Tool
----@param opts table
+---@param meta table
 ---@return nil
-M.rejected = function(self, opts)
```
Comment (olimorris) [inline lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua:9]: Renaming this parameter should be outside the scope of what this PR does.

Changes like this muddy the review and take away from what this PR fixes

File: Makefile
Comment (olimorris) [inline Makefile:1]: Please revert

File: tests/interactions/chat/tools/runtime/test_user_approval.lua
Comment (olimorris) [inline tests/interactions/chat/tools/runtime/test_user_approval.lua:1]: We don't two similar tests in two different locations

**Review by olimorris — COMMENTED** [review]
Your agent has done some odd things which are outside of the scope of what this PR should be.

Changing the make file, altering parameter names, adding duplicate tests.

File: lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua (hunk 1 above)
Comment (cairijun) [reply lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua:9]: This is an intended change. The root cause is not about using a wrong field, but an incomplete refactor in #2740 -- `tools` and `cmd` parameters were removed and leaving `opts` at where `meta` should be.

File: Makefile
Comment (cairijun) [reply Makefile:1]: Tests break on my env without it. But I double checked and confirmed that is not related to this fix. Will revert.

File: tests/interactions/chat/tools/runtime/test_user_approval.lua
Comment (cairijun) [reply tests/interactions/chat/tools/runtime/test_user_approval.lua:1]: I explicitly ask the agent to add tests at multiple layers -- one for the interop between `helpers.reject` and `Orchestrator`, and another one verifying a more complete and typical use case. I don't see a clear layered design in the existing tests so I choose these two locations which seem appropriate to me. If you prefer keeping only one test for this fix, I will revert another one.

File: lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua (hunk 1 above)
Comment (olimorris) [reply lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua:9]: I figured it was intended because you commited it. What I mean is, this PR should be focussed on fixing the reason rejection reasons aren't being passed to the LLM. We're merging a refactor into a fix.

Comment (cairijun) [reply lua/codecompanion/interactions/chat/tools/builtin/helpers/init.lua:9]: Oh, I understand your intention. Let's do this your way.
It's just a bit different from our team's convention to "seize opportunities for micro refactorings in relevant code" to reduce CR round trips.

File: tests/interactions/chat/tools/runtime/test_user_approval.lua
Comment (cairijun) [reply tests/interactions/chat/tools/runtime/test_user_approval.lua:1]: And what's your idea about this? Should we keep just the one in `test_user_approval`?

**Comment by olimorris** [comment]
Thanks for your efforts on this. I reverted the changes to bring this PR into scope.

The test localisation environment variable was moved into #2928. Great suggestion on that.
