### PR TITLE
Failed/cancelled/rejected tool calls no longer block the execution queue

### LINKED ISSUE #1850: [Bug]: `Bad Request` after partial tool call failures with Github Copilot
### Pre-submission checklist

- [x] I have read the [documentation](https://codecompanion.olimorris.dev)
- [x] I have updated the plugin and all dependencies to the latest versions
- [x] I have searched for existing [issues](https://github.com/olimorris/codecompanion.nvim/issues) and [discussions](https://github.com/olimorris/codecompanion.nvim/discussions)
- [x] My issue is not a minor or cosmetic quirk (e.g., formatting, spacing, or other non-functional details)

### Neovim version (nvim -v)

v0.12.0-dev-768+gf576b59a09

### Operating system/version

Linux

### Adapter and model

Github Copilot with gpt-4.1

### Describe the bug

When Copilot tries to do multiple tool calls in one response but some of them fail, it may stuck in `Bad Request` errors for all subsequent requests.

My guess is that Copilot expects results of ALL tool calls, whether succeeded, failed or being skipped. But CodeCompanion would stop tool execution when any of them failed or rejected, and not generate results for the skipped tool calls.

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. `:CodeCompanionChat`
3. Enter:
    ```
    @{files}
    Read the following files and make a summary.
    * `/tmp/xxx/sample/error1.txt`
    * `/tmp/xxx/sample/error2.txt`
    * `/tmp/xxx/sample/error3.txt`
    ```
4. Wait for the file read error.
5. Enter: `Ignore this error.`
6. Copilot responses `Bad Request`, and we are stuck here unless we manually fix the chat with the debug panel.
7. `gd`, remove the tool calls that were skipped.
8. The chat can continue now.

### Expected behavior

We should be able to continue this chat, either let the LLM ignore the errors or instruct it revise its tool call requests.

CodeCompanion should either keep running other tool calls, or generate dummy results for them to let the LLM know these tool calls were skipped.

### Screenshots or recordings (optional)

```lua
{ {
    content = "You are an AI programming assistant named \"CodeCompanion\". You are currently plugged into the Neovim text editor on a user's machine.\n\nYour core tasks include:\n- Answering general programming questions.\n- Explaining how the code in a Neovim buffer works.\n- Reviewing the selected code from a Neovim buffer.\n- Generating unit tests for the selected code.\n- Proposing fixes for problems in the selected code.\n- Scaffolding code for a new workspace.\n- Finding relevant code to the user's query.\n- Proposing fixes for test failures.\n- Answering questions about Neovim.\n- Running tools.\n\nYou must:\n- Follow the user's requirements carefully and to the letter.\n- Use the context and attachments the user provides.\n- Keep your answers short and impersonal, especially if the user's context is outside your core tasks.\n- Minimize additional prose unless clarification is needed.\n- Use Markdown formatting in your answers.\n- Include the programming language name at the start of each Markdown code block.\n- Do not include line numbers in code blocks.\n- Avoid wrapping the whole response in triple backticks.\n- Only return code that's directly relevant to the task at hand. You may omit code that isn’t necessary for the solution.\n- Avoid using H1, H2 or H3 headers in your responses as these are reserved for the user.\n- Use actual line breaks in your responses; only use \"\\n\" when you want a literal backslash followed by 'n'.\n- All non-code text responses must be written in the English language indicated.\n- Multiple, different tools can be called as part of the same response.\n\nWhen given a task:\n1. Think step-by-step and, unless the user requests otherwise or the task is very simple, describe your plan in detailed pseudocode.\n2. Output the final code in a single code block, ensuring that only relevant code is included.\n3. End your response with a short suggestion for the next user turn that directly supports continuing the conversation.\n4. Provide exactly one complete reply per conversation turn.\n5. If necessary, execute multiple tools in a single turn.",
    cycle = 1,
    id = 126646444,
    opts = {
      tag = "from_config",
      visible = false
    },
    role = "system"
  }, {
    content = "create_file, file_search, get_changed_files, grep_search, insert_edit_into_file, read_file\nRead the following files and make a summary.\n\n* `/tmp/xxx/sample/error1.txt`\n* `/tmp/xxx/sample/error2.txt`\n* `/tmp/xxx/sample/error3.txt`",
    cycle = 1,
    id = 575788808,
    opts = {
      visible = true
    },
    role = "user"
  }, {
    content = "<editFileInstructions>\nBefore editing a file, ensure you have its content via the provided context or read_file tool.\nUse the insert_edit_into_file tool to modify files.\nNEVER show the code edits to the user - only call the tool. The system will apply and display the edits.\nFor each file, give a short description of what needs to be edited, then use the insert_edit_into_file tools. You can use the tool multiple times in a response, and you can keep writing text after using a tool.\nThe insert_edit_into_file tool is very smart and can understand how to apply your edits to the user's files, you just need to follow the patch format instructions carefully and to the letter.\n\n## Patch Format\n*** Begin Patch\n[PATCH]\n*** End Patch\n\nThe `[PATCH]` is the series of diffs to be applied for each edit in the file. Each diff should be in this format:\n\n [3 lines of pre-context]\n-[old code]\n+[new code]\n [3 lines of post-context]\n\nThe context blocks are 3 lines of existing code, immediately before and after the modified lines of code.\nLines to be modified should be prefixed with a `+` or `-` sign.\nUnmodified lines used in context should begin with an empty space ` `.\n\nFor example, to add a subtract method to a calculator class in Python:\n\n*** Begin Patch\n def add(self, value):\n     self.result += value\n     return self.result\n\n+def subtract(self, value):\n+    self.result -= value\n+    return self.result\n+\n def multiply(self, value):\n     self.result *= value\n     return self.result\n*** End Patch\n\nMultiple blocks of diffs should be separated by an empty line and `@@[identifier]` as detailed below.\nThe immediately preceding and after context lines are enough to locate the lines to edit. DO NOT USE line numbers anywhere in the patch.\nYou can use `@@[identifier]` to define a larger context in case the immediately before and after context is not sufficient to locate the edits. Example:\n\n@@class BaseClass(models.Model):\n [3 lines of pre-context]\n-\tpass\n+\traise NotImplementedError()\n [3 lines of post-context]\n\nYou can also use multiple `@@[identifiers]` to provide the right context if a single `@@` is not sufficient.\nExample with multiple blocks of edits and `@@` identifiers:\n\n*** Begin Patch\n@@class BaseClass(models.Model):\n@@\tdef search():\n-\t\tpass\n+\t\traise NotImplementedError()\n\n@@class Subclass(BaseClass):\n@@\tdef search():\n-\t\tpass\n+\t\traise NotImplementedError()\n*** End Patch\n\nThis format is similar to the `git diff` format; the difference is that `@@[identifiers]` uses the unique line identifiers from the preceding code instead of line numbers. We don't use line numbers anywhere since the before and after context, and `@@` identifiers are enough to locate the edits.\nIMPORTANT: Be mindful that the user may have shared attachments that contain line numbers, but these should NEVER be used in your patch. Always use the contextual format described above.The system uses fuzzy matching and confidence scoring so focus on providing enough context to uniquely identify the location.\n</editFileInstructions>",
    cycle = 1,
    id = 391413238,
    opts = {
      reference = "<tool>insert_edit_into_file</tool>",
      tag = "tool",
      visible = false
    },
    role = "system"
  }, {
    cycle = 1,
    id = 197288128,
    opts = {
      visible = false
    },
    role = "llm",
    tool_calls = { {
        _index = 0,
        ["function"] = {
          arguments = '{"filepath": "/tmp/xxx/sample/error1.txt", "start_line_number_base_zero": 0, "end_line_number_base_zero": -1}',
          name = "read_file"
        },
        id = "call_qAqGfdCJct7EXIRFwf3q9Dsy",
        type = "function"
      }, {
        _index = 1,
        ["function"] = {
          arguments = '{"filepath": "/tmp/xxx/sample/error2.txt", "start_line_number_base_zero": 0, "end_line_number_base_zero": -1}',
          name = "read_file"
        },
        id = "call_Y8rqGdpvtiCeSithQ6uOQHPI",
        type = "function"
      }, {
        _index = 2,
        ["function"] = {
          arguments = '{"filepath": "/tmp/xxx/sample/error3.txt", "start_line_number_base_zero": 0, "end_line_number_base_zero": -1}',
          name = "read_file"
        },
        id = "call_ZwRXKo1htySBl6603p7kScVL",
        type = "function"
      } }
  }, {
    content = "Error reading `/tmp/tmp/xxx/sample/error1.txt`, does not exist",
    cycle = 1,
    id = 1730352165,
    opts = {
      visible = true
    },
    role = "tool",
    tool_call_id = "call_qAqGfdCJct7EXIRFwf3q9Dsy"
  }, {
    content = "Ignore this error.",
    cycle = 2,
    id = 2036909938,
    opts = {
      visible = true
    },
    role = "user"
  } }
```

### minimal.lua file

```lua
https://github.com/olimorris/codecompanion.nvim/blob/164e95c6ff0becd6d152e06be56ccd98f53bc5a8/minimal.lua
```

### Log output (optional)

```log
[DEBUG] 2025-07-16 11:04:24
[Tools] strategies.chat.agents.tools.create_file identified
[DEBUG] 2025-07-16 11:04:24
[Tools] strategies.chat.agents.tools.file_search identified
[DEBUG] 2025-07-16 11:04:24
[Tools] strategies.chat.agents.tools.get_changed_files identified
[DEBUG] 2025-07-16 11:04:24
[Tools] strategies.chat.agents.tools.grep_search identified
[DEBUG] 2025-07-16 11:04:24
[Tools] strategies.chat.agents.tools.insert_edit_into_file identified
[DEBUG] 2025-07-16 11:04:24
[Tools] strategies.chat.agents.tools.read_file identified
[INFO] 2025-07-16 11:04:24
Chat request started
[DEBUG] 2025-07-16 11:04:24
Authorizing GitHub Copilot token
[INFO] 2025-07-16 11:04:26
Request body file: /data/tmp/nvim.rwoEg3/1.json
[DEBUG] 2025-07-16 11:04:26
Request:
{ "-sSL", "-D", "/tmp/plenary_curl_f4574a9c.headers", "-X", "POST", "-H", "Content-Type: application/json", "-H", "Copilot-Integration-Id: vscode-chat", "-H", "Editor-Version: Neovim/0.12.0", "-H", "Authorization: ****", "-d", "@/data/tmp/nvim.rwoEg3/1.json", "--retry", "3", "--retry-delay", "1", "--keepalive-time", "60", "--connect-timeout", "10", "--tcp-nodelay", "--no-buffer", "https://api.individual.githubcopilot.com/chat/completions" }
[DEBUG] 2025-07-16 11:04:29
[Tools] strategies.chat.agents.tools.read_file identified
[DEBUG] 2025-07-16 11:04:29
[Tools] strategies.chat.agents.tools.read_file identified
[DEBUG] 2025-07-16 11:04:29
[Tools] strategies.chat.agents.tools.read_file identified
[INFO] 2025-07-16 11:04:29
[Agent] Initiated
[DEBUG] 2025-07-16 11:04:29
Executor:execute - `read_file` tool
[DEBUG] 2025-07-16 11:04:29
FuncExecutor:orchestrate 1
[DEBUG] 2025-07-16 11:04:29
Args: {
  end_line_number_base_zero = -1,
  filepath = "/tmp/xxx/sample/error1.txt",
  start_line_number_base_zero = 0
}
[DEBUG] 2025-07-16 11:04:29
FuncExecutor:run
[DEBUG] 2025-07-16 11:04:29
Executor:error
[WARN] 2025-07-16 11:04:30
Tool read_file: Error reading `/tmp/tmp/xxx/sample/error1.txt`, does not exist
[DEBUG] 2025-07-16 11:04:30
[Read File Tool] Error output: { "Error reading `/tmp/tmp/xxx/sample/error1.txt`, does not exist" }
[DEBUG] 2025-07-16 11:04:30
Tool output: {
  _index = 0,
  ["function"] = {
    arguments = '{"filepath": "/tmp/xxx/sample/error1.txt", "start_line_number_base_zero": 0, "end_line_number_base_zero": -1}',
    name = "read_file"
  },
  id = "call_qAqGfdCJct7EXIRFwf3q9Dsy",
  type = "function"
}
[DEBUG] 2025-07-16 11:04:30
Executor:close
[INFO] 2025-07-16 11:04:30
Chat request finished
[INFO] 2025-07-16 11:04:30
[Agent] Completed
[INFO] 2025-07-16 11:04:42
Chat request started
[INFO] 2025-07-16 11:04:42
Request body file: /data/tmp/nvim.rwoEg3/2.json
[DEBUG] 2025-07-16 11:04:42
Request:
{ "-sSL", "-D", "/tmp/plenary_curl_a3924d90.headers", "-X", "POST", "-H", "Content-Type: application/json", "-H", "Copilot-Integration-Id: vscode-chat", "-H", "Editor-Version: Neovim/0.12.0", "-H", "Authorization: ****", "-d", "@/data/tmp/nvim.rwoEg3/2.json", "--retry", "3", "--retry-delay", "1", "--keepalive-time", "60", "--connect-timeout", "10", "--tcp-nodelay", "--no-buffer", "https://api.individual.githubcopilot.com/chat/completions" }
[ERROR] 2025-07-16 11:04:44
Error: Bad Request
```

### Minimal reproduction confirmation

- [x] Yes, I have tested and provided a `minimal.lua` file that reproduces the issue

### PR DESCRIPTION
**Pull request by Davidyz**
## Description

This PR makes sure all `tool_calls` have a corresponding response by:

- make sure interrupted tool calls doesn't abort the subsequent tool calls.
- add fallback tool output handlers so that tools always send something to the LLM to indicate the result status.

## Related Issue(s)

Fix #1850 

## Checklist

- [x] I've read the [contributing](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [ ] I've updated `CodeCompanion.has` in the [init.lua](https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/init.lua#L239) file for my new feature
- [ ] I've added [test](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md#testing) coverage for this fix/feature
- [x] I've updated the README and/or relevant docs pages
- [ ] I've run `make all` to ensure docs are generated, tests pass and my formatting is applied

### CODE REVIEW

**Comment by olimorris** [comment]
Heads up, I'm going to take a look at the issue later on this week. The fix needs to be the continued running of tools even if an error is encountered

**Comment by Davidyz** [comment]
> Heads up, I'm going to take a look at the issue later on this week. The fix needs to be the continued running of tools even if an error is encountered

Ok no worries. Turns out this is harder than I thought. Also, we should probably take the cancelled tool into account because it could also cause the subsequent tool calls to be aborted.

**Comment by olimorris** [comment]
That's a good point as well!

**Comment by Davidyz** [comment]
Almost there
image

**Comment by olimorris** [comment]
Firstly, amazing job. Secondly, I'm surprised this didn't break any tests.

**Comment by Davidyz** [comment]
> Firstly, amazing job. Secondly, I'm surprised this didn't break any tests.

Looks like there wasn't any test coverage on interrupted queues. I'm trying to write some tests, but they're not happy with my patch. There's probably something wrong with my patch.

File: lua/codecompanion/strategies/chat/agents/executor/init.lua [hunk 1]
```diff
@@ -210,9 +228,13 @@ end
 ---Close the execution of the tool
 ---@return nil
 function Executor:close()
-  log:debug("Executor:close")
-  self.handlers.on_exit()
-  util.fire("ToolFinished", { id = self.id, name = self.tool.name, bufnr = self.agent.bufnr })
+  if self.tool then
```
Comment (Davidyz) [inline lua/codecompanion/strategies/chat/agents/executor/init.lua:236]: The new test case failed with the following output:
```
tests/strategies/chat/agents/executor/test_queue.lua: ox

Fails (1) and Notes (0)
FAIL in tests/strategies/chat/agents/executor/test_queue.lua | Agent | queue | can proceed on error:
  Failed expectation for equality.
  Left:  "Func[Setup]->Func[Success]->Func[Exit]->Cmd[Setup]->Cmd[Error]->Cmd[Exit]->Func2[Setup]->Func2[Success]->Func2[Exit]"
  Right: "Func[Setup]->Func[Success]->Func[Exit]->Cmd[Setup]->Cmd[Error]->Cmd[Exit]->Func2[Setup]->Func2[Success]->Func2[Exit]->Func2[Exit]"
  Traceback:
    tests/strategies/chat/agents/executor/test_queue.lua:99
```
It indicates that the `on_exit` method of the tool was called twice.

This is a workaround that avoids the `close` method being called more than once. It's probably not the best way to fix it, but it makes the new test pass.

Comment (olimorris) [reply lua/codecompanion/strategies/chat/agents/executor/init.lua:236]: Should `executor:close` reset `self.agent.status` after it executes? I'm wondering if, by not doing this, then the logic on L119-L122 is called

Comment (Davidyz) [reply lua/codecompanion/strategies/chat/agents/executor/init.lua:236]: At the moment it's the other way around. `setup` calls `close` to make sure the failed tool is cleaned. Commenting out L121 and reseting `self.agent.status` in `close` broke the new test (`Cmd[Exit]` was missing).

In fact this made me wondering, now that the function-based tool supports callback style async, do we really need to keep the cmd executor? I think we can just drop the cmd executor and make a wrapper that transforms command based tools into function based tools that calls `plenary.job` or simply `vim.system`. This should simplify the executor, and we won't have to worry about all the different combinations in the tool queues when writing tests.

Comment (olimorris) [reply lua/codecompanion/strategies/chat/agents/executor/init.lua:236]: No we don't. That's a great point.

This PR should go in as a fix. But I am absolutely up for a refactor PR that removes the cmd executor.

This PR is good from my side. You happy for me to merge it?

Comment (Davidyz) [reply lua/codecompanion/strategies/chat/agents/executor/init.lua:236]: yep I didn't intend to include the refactoring in this PR either. I think we're good to go.

(tbh I wanted to dig deeper and try to find out why `on_exit` was called twice, but if we're having a refactoring, it's probably easier to just come back to it after that.)

**Comment by olimorris** [comment]
Awesome. Thanks again for your work on this PR.
