### PR TITLE
fix: delete diff buffers instead of closing

### LINKED ISSUE #851: [Bug]: Diff buffers remain after closing
### Your `minimal.lua` config

```lua
---@diagnostic disable: missing-fields

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
      { "nvim-lua/plenary.nvim" },
    },
    opts = {
      --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      strategies = {
        --NOTE: Change the adapter as required
        chat = { adapter = "ollama" },
        inline = { adapter = "ollama" },
      },
      adapters = {
        coder = function()
          return require("codecompanion.adapters").extend("ollama", {
            schema = {
              model = {
                default = 'qwen2.5-coder:14b',
              },
              num_ctx = {
                default = 8192,
              },
            },
          })
        end,
      },
      opts = {
        log_level = "DEBUG",
      },
    },
  },
}

require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
  treesitter.setup({
    ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
    highlight = { enable = true },
  })
end
```

### Error messages

_No response_

### Log output

```
[DEBUG] 2025-02-06 22:16:42
Messages:
{ {
    content = "You are an AI programming assistant named \"CodeCompanion\".\nYou are currently plugged in to the Neovim text editor on a user's machine.\n\nYour core tasks include:\n- Answering general programming questions.\n- Explaining how the code in a Neovim buffer works.\n- Reviewing the selected code in a Neovim buffer.\n- Generating unit tests for the selected code.\n- Proposing fixes for problems in the selected code.\n- Scaffolding code for a new workspace.\n- Finding relevant code to the user's query.\n- Proposing fixes for test failures.\n- Answering questions about Neovim.\n- Running tools.\n\nYou must:\n- Follow the user's requirements carefully and to the letter.\n- Keep your answers short and impersonal, especially if the user responds with context outside of your tasks.\n- Minimize other prose.\n- Use Markdown formatting in your answers.\n- Include the programming language name at the start of the Markdown code blocks.\n- Avoid including line numbers in code blocks.\n- Avoid wrapping the whole response in triple backticks.\n- Only return code that's relevant to the task at hand. You may not need to return all of the code that the user has shared.\n- Use actual line breaks instead of '\\n' in your response to begin new lines.\n- Use '\\n' only when you want a literal backslash followed by a character 'n'.\n- All non-code responses must be in English.\n\nWhen given a task:\n1. Think step-by-step and describe your plan for what to build in pseudocode, written out in great detail, unless asked not to do so.\n2. Output the code in a single code block, being careful to only return relevant code.\n3. You should always generate short suggestions for the next user turns that are relevant to the conversation.\n4. You can only give one reply for each conversation turn.",
    cycle = 1,
    id = 1628281114,
    opts = {
      tag = "from_config",
      visible = false
    },
    role = "system"
  }, {
    content = "Add several lines of text to the buffer.",
    cycle = 1,
    id = 1524405380,
    opts = {
      visible = true
    },
    role = "user"
  }, {
    content = "## Tools\n\nYou now have access to tools:\n- These enable you to assist the user with specific tasks\n- The user will outline which specific tools you have access to\n- You trigger a tool by following a specific XML schema which is defined for each tool\n\nYou must:\n- Only use the tool when prompted by the user, despite having access to it\n- Follow the specific tool's schema\n- Respond with the schema in XML format\n- Ensure the schema is in a markdown code block that is designated as XML\n- Ensure any output you're intending to execute will be able to parsed as valid XML\n\nPoints to note:\n- The user detects that you've triggered a tool by using Tree-sitter to parse your markdown response\n- If you call multiple tools within the same response:\n  - Each unique tool MUST be called in its own, individual, XML codeblock\n  - Tools of the same type SHOULD be called in the same XML codeblock\n- If your response doesn't follow the tool's schema, the tool will not execute\n- Tools should not alter your core tasks and how you respond to a user",
    cycle = 1,
    id = 1255510772,
    opts = {
      reference = "tool_system_prompt",
      tag = "tool",
      visible = false
    },
    role = "system"
  }, {
    content = "### Editor Tool\n\n1. **Purpose**: Update the contents of a Neovim buffer\n\n2. **Usage**: Return an XML markdown code block for add, update, or delete operations.\n\n3. **Key Points**:\n  - **Only use when prompted** by user (e.g., \"can you update the code?\", \"update the buffer...\")\n  - Ensure XML is **valid and follows the schema**\n  - **Include indentation** in your code\n  - **Don't escape** special characters\n  - **Wrap code in a CDATA block**, the code could contain characters reserved by XML\n  - Make sure the tools xml block is **surrounded by ```xml**\n\n4. **Actions**:\n\na) Add:\n\n```xml\n<tools>\n  <tool name=\"editor\">\n    <action type=\"add\">\n      <code><![CDATA[    print('Hello World')]]></code>\n      <buffer>1</buffer>\n      <line>203</line>\n    </action>\n  </tool>\n</tools>\n```\n\nb) Update:\n\n```xml\n<tools>\n  <tool name=\"editor\">\n    <action type=\"update\">\n      <start_line>199</start_line>\n      <buffer>10</buffer>\n      <code><![CDATA[   function M.capitalize()]]></code>\n      <end_line>199</end_line>\n    </action>\n  </tool>\n</tools>\n```\n\nc) Delete:\n\n```xml\n<tools>\n  <tool name=\"editor\">\n    <action type=\"delete\">\n      <start_line>10</start_line>\n      <buffer>14</buffer>\n      <end_line>15</end_line>\n    </action>\n  </tool>\n</tools>\n```\n\n5. **Multiple Actions**: Combine actions in one response if needed:\n\n```xml\n<tools>\n  <tool name=\"editor\">\n    <action type=\"delete\">\n      <start_line>13</start_line>\n      <buffer>5</buffer>\n      <end_line>13</end_line>\n    </action>\n    <action type=\"add\">\n      <code><![CDATA[function M.hello_world()]]></code>\n      <buffer>5</buffer>\n      <line>20</line>\n    </action>\n  </tool>\n</tools>\n```\n\n6. **Note**:\n  - The tool can handle multiple actions in one response such as adding and deleting code\n  - For the delete action, the <start_line> and <end_line> tags are inclusive\n  - The update action first deletes the range in <start_line> and <end_line> (inclusively) and then adds new code from the <start_line>\n  - If you need to update a single line, set <start_line> and <end_line> to the same value in the update action\n  - Remember you can have multiple update actions after one another.\n  - Account for comment blocks and indentation in your code\n  - If the user supplies no context, it can be assumed that they would like you to update the buffer with the code from your last response\n\nRemember: Minimize explanations unless prompted. Focus on generating correct XML.",
    cycle = 1,
    id = 705388009,
    opts = {
      reference = "<tool>editor</tool>",
      tag = "tool",
      visible = false
    },
    role = "system"
  }, {
    content = "Here is the content from the buffer.\n\nBuffer ID: 1\nName: \nPath: \nFiletype: \nContent:\n```\n1:  \n```\n",
    cycle = 1,
    id = 956996558,
    opts = {
      reference = "<buf>Buffer 1</buf>",
      tag = "variable",
      visible = false
    },
    role = "user"
  }, {
    content = '```xml\n<tools>\n  <tool name="editor">\n    <action type="add">\n      <code><![CDATA[\nnew_line_1()\nnew_line_2()\nnew_line_3()\n]]></code>\n      <buffer>1</buffer>\n      <line>1</line>\n    </action>\n  </tool>\n</tools>\n```',
    cycle = 1,
    id = 1703452099,
    opts = {
      visible = true
    },
    role = "llm"
  }, {
    content = "Replace the buffer contents with several new lines.",
    cycle = 2,
    id = 159881658,
    opts = {
      visible = true
    },
    role = "user"
  }, {
    content = '```xml\n<tools>\n  <tool name="editor">\n    <action type="delete">\n      <start_line>1</start_line>\n      <buffer>1</buffer>\n      <end_line>1</end_line>\n    </action>\n    <action type="add">\n      <code><![CDATA[\nline_one()\nline_two()\nline_three()\nline_four()\n]]></code>\n      <buffer>1</buffer>\n      <line>1</line>\n    </action>\n  </tool>\n</tools>\n```',
    cycle = 2,
    id = 1391866450,
    opts = {
      visible = true
    },
    role = "llm"
  }, {
    content = "Replace the entire buffer contents with some new text.",
    cycle = 3,
    id = 1613566492,
    opts = {
      visible = true
    },
    role = "user"
  }, {
    content = '```xml\n<tools>\n  <tool name="editor">\n    <action type="delete">\n      <start_line>1</start_line>\n      <buffer>1</buffer>\n      <end_line>-1</end_line>\n    </action>\n    <action type="add">\n      <code><![CDATA[\nfirst_new_line()\nsecond_new_line()\nthird_new_line()\n]]></code>\n      <buffer>1</buffer>\n      <line>1</line>\n    </action>\n  </tool>\n</tools>\n```',
    cycle = 3,
    id = 1043804615,
    opts = {
      visible = true
    },
    role = "llm"
  }, {
    content = "Replace the entire buffer contents with a single line of text.",
    cycle = 4,
    id = 1639799719,
    opts = {
      visible = true
    },
    role = "user"
  } }
[INFO] 2025-02-06 22:16:42
Chat request started
[INFO] 2025-02-06 22:16:42
ELAPSED TIME: 19.199565
[INFO] 2025-02-06 22:16:42
Request body file: /tmp/nvim.taylor/2bL825/3.json
[DEBUG] 2025-02-06 22:16:42
Request:
{ "-sSL", "-D", "/run/user/1000/plenary_curl_ecba4d00.headers", "-X", "POST", "-d", "@/tmp/nvim.taylor/2bL825/3.json", "--retry", "3", "--retry-delay", "1", "--keepalive-time", "60", "--connect-timeout", "10", "--tcp-nodelay", "--no-buffer", "http://localhost:11434/api/chat" }
[DEBUG] 2025-02-06 22:16:47
Done! 102
[DEBUG] 2025-02-06 22:16:47
[Tools] Detected: { '<tools>\n  <tool name="editor">\n    <action type="delete">\n      <start_line>1</start_line>\n      <buffer>1</buffer>\n      <end_line>-1</end_line>\n    </action>\n    <action type="add">\n      <code><![CDATA[\nSingle line of text.]]></code>\n      <buffer>1</buffer>\n      <line>1</line>\n    </action>\n  </tool>\n</tools>' }
[DEBUG] 2025-02-06 22:16:47
[Tools] Calling strategies.chat.tools.editor
[DEBUG] 2025-02-06 22:16:47
Agent started
[DEBUG] 2025-02-06 22:16:47
[Tools] Running cmd: function: 0x7460dccb4308
[DEBUG] 2025-02-06 22:16:47
Editor tool request: {
  _attr = {
    type = "delete"
  },
  buffer = "1",
  end_line = "-1",
  start_line = "1"
}
[DEBUG] 2025-02-06 22:16:47
Editor tool request: {
  _attr = {
    type = "add"
  },
  buffer = "1",
  code = "\nSingle line of text.",
  line = "1"
}
[INFO] 2025-02-06 22:16:47
Chat request finished
[DEBUG] 2025-02-06 22:16:47
Agent Finished
[DEBUG] 2025-02-06 22:16:47
[Tools] Finished EDITOR
[DEBUG] 2025-02-06 22:16:47
Agent finished
```

### Describe the bug

What I expect to happen:

I expect to be able to ask an LLM to modify the buffer multiple times and for the diffs to make sense and apply cleanly.

What actually happens:

As more changes are made the diffs get more and more complicated and it takes longer and longer to populate the diff. Often, the diffs no longer seem to make sense.

Image

Above is an example of a diff that makes no sense. Both sides of the diff show line deletions in the same place. For reference, here is what the diff ought to look like:

Image

What I suspect is the cause:

As you can see in the top screenshot, several unlisted CodeCompanion buffers are present. I believe CodeCompanion is not properly cleaning up the temporary diff buffers it creates. It closes the diff buffers it no longer needs, but it does not call "diffoff" ("diffoff" is called on the [buffer being edited](https://github.com/olimorris/codecompanion.nvim/blob/e54ec7499513055077ce20f81d95de7ae60f2537/lua/codecompanion/providers/diff/default.lua#L111) but not on the temporary diff buffer) nor does it delete them. Thus, when a new diff buffer is created neovim tries to calculate a diff between all of the still-present buffers.

Proposed solution:

Rather than [closing](https://github.com/olimorris/codecompanion.nvim/blob/e54ec7499513055077ce20f81d95de7ae60f2537/lua/codecompanion/providers/diff/default.lua#L112) the diff buffer on teardown, I think the buffer should be deleted using `api.nvim_buf_delete`. I have tested this locally and it solves the issue for me. I plan to open a PR with this change shortly.

### Reproduce the bug

Steps to reproduce:

1. Ask the LLM to add several lines to an empty buffer and accept diff.
2. Ask the LLM to replace the buffer contents with several new lines and accept diff.
3. Ask the LLM to replace the buffer contents with a single line.

### Adapter and model

ollama and qwen2.5-coder:14b

### Final checks

- [x] I have made sure this issue exists in the latest version of the plugin
- [x] I have tested with the `minimal.lua` file from above and have shared this
- [x] I have shared the contents of the log file

### PR DESCRIPTION
**Pull request by taylorskalyo**
## Description

When closed, a diff buffer still exists (it's just hidden and unlisted). It also keeps "diffthis" set. This can lead to complicated and confusing diffs as the number of dangling buffers increases.

Since diff buffers are temporary and not re-used it should be safe to delete them instead of closing them.

## Related Issue(s)

- Fixes #851

## Checklist

- [x] I've read the [contributing](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [ ] I've updated the README and/or relevant docs pages

### CODE REVIEW

File: lua/codecompanion/providers/diff/default.lua [hunk 1]
```diff
@@ -109,7 +109,7 @@ end
 ---@return nil
 function Diff:teardown()
   vim.cmd("diffoff")
-  api.nvim_win_close(self.diff.win, false)
+  api.nvim_buf_delete(self.diff.buf, {})
```
Comment (olimorris) [inline lua/codecompanion/providers/diff/default.lua:112]: Great spot. I think we also need to have `api.nvim_win_close(self.diff.win, false)` after this as this closes the diff window we've created

Comment (taylorskalyo) [reply lua/codecompanion/providers/diff/default.lua:112]: Thanks for the quick reply! I gave that a shot, and this is what I found.

```diff
diff --git a/lua/codecompanion/providers/diff/default.lua b/lua/codecompanion/providers/diff/default.lua
index 6a87f53..059a17b 100644
--- a/lua/codecompanion/providers/diff/default.lua
+++ b/lua/codecompanion/providers/diff/default.lua
@@ -109,6 +109,7 @@ end
 ---@return nil
 function Diff:teardown()
   vim.cmd("diffoff")
+  api.nvim_buf_delete(self.diff.buf, {})
   api.nvim_win_close(self.diff.win, false)
   util.fire("DiffDetached", { diff = "default", bufnr = self.bufnr })
 end
```

With `nvim_buf_delete` followed by `nvim_win_close` as shown above, I get the following error when accepting or rejecting a diff:

```
E5108: Error executing lua: ...panion.nvim/lua/codecompanion/providers/diff/default.lua:113: Invalid window id: 1007
stack traceback:
        [C]: in function 'nvim_win_close'
        ...panion.nvim/lua/codecompanion/providers/diff/default.lua:113: in function 'teardown'
        ...panion.nvim/lua/codecompanion/providers/diff/default.lua:104: in function 'reject'
        ...ion.nvim/lua/codecompanion/strategies/inline/keymaps.lua:31: in function 'rhs'
        ...y/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:74: in function <...y/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:71>
```

Looking more closely at the docs, I can see that `nvim_buf_delete` not only removes the buffer but also closes the window.

nvim_buf_delete({buffer}, {opts}) [nvim_buf_delete()](https://neovim.io/doc/user/api.html#nvim_buf_delete())
> Deletes the buffer. See [:bwipeout](https://neovim.io/doc/user/windows.html#%3Abwipeout)

[:bw](https://neovim.io/doc/user/windows.html#%3Abw) [:bwipe](https://neovim.io/doc/user/windows.html#%3Abwipe) [:bwipeout](https://neovim.io/doc/user/windows.html#%3Abwipeout) [E517](https://neovim.io/doc/user/windows.html#E517)
>  Like [:bdelete](https://neovim.io/doc/user/windows.html#%3Abdelete), but really delete the buffer.

[:bd](https://neovim.io/doc/user/windows.html#%3Abd) [:bdel](https://neovim.io/doc/user/windows.html#%3Abdel) [:bdelete](https://neovim.io/doc/user/windows.html#%3Abdelete) [E516](https://neovim.io/doc/user/windows.html#E516)
> Unload buffer [N] (default: current buffer) and delete it from
> the buffer list.  If the buffer was changed, this fails,
> unless when [!] is specified, in which case changes are lost.
> The file remains unaffected.  **Any windows for this buffer are
> closed.**

This is what I've observed in practice as well. With just the `nvim_buf_delete` call present, the diff window disappears as expected when a diff is accepted or rejected.
