### PR TITLE
chore: fix tests on native windows

### LINKED ISSUE #2199: [Bug]: Some tests fail on windows
### Pre-submission checklist

- [x] I have read the [documentation](https://codecompanion.olimorris.dev)
- [x] I have updated the plugin and all dependencies to the latest versions
- [x] I have searched for existing [issues](https://github.com/olimorris/codecompanion.nvim/issues) and [discussions](https://github.com/olimorris/codecompanion.nvim/discussions)
- [x] My issue is not a minor or cosmetic quirk (e.g., formatting, spacing, or other non-functional details)

### Neovim version (nvim -v)

0.11.4

### Operating system/version

Windows 11

### Adapter and model

Copilot

### Describe the bug

Not all tests run/pass on Windows, mostly due to issues with path separators.

I mentioned in #2186 I'd take a look at getting tests to pass on Windows.

### Steps to reproduce

`neovim --headless --noplugin -u scripts/minimal_init.lua -c 'lua MiniTest.run()'`

### Expected behavior

Tests should pass, or, rather, should not fail due to issues with path separators (`\` vs `/`)

### Screenshots or recordings (optional)

_No response_

### minimal.lua file

```lua
-- irrelevant
```

### Log output (optional)

_No response_

### Minimal reproduction confirmation

- [x] Yes, I have tested and provided a `minimal.lua` file that reproduces the issue

### PR DESCRIPTION
**Pull request by alzwded**
## Description

While working on #2186 , particularly when adding coverage, I noticed a few tests are failing.

Added `run_tests.cmd` which functionally does what `make test` is supposed to do. This also makes sure `$HOME` is set, which normally isn't a thing on Windows.

❗ In `‎lua/codecompanion/utils/buffers.lua`, switch forward slashes to backslashes on Windows, because `fnamemodify(..., :.)` would refuse to work otherwise.

In `lua\codecompanion\strategies\chat\helpers\init.lua`, perform additional path normalization around the call to `cwd()`, as it is returned with backslashes on Windows.

Some tests that run shell commands need to wait a little bit longer on Windows, because that's how things are over there, slow.

Usually it was a matter of coping with slashes of the wrong orientation.

## Related Issue(s)

- Fixes #2199 

## Screenshots

How about a giant log?

<details>
<summary>Tests on Windows on main HEAD</summary>

    c:\D\Projects\codecompanion.nvim>nvim --headless --noplugin -u ./scripts/minimal_init.lua -c "lua MiniTest.run()"
    `adapters.<adapter_name>` and `adapters.opts` is deprecated, use `adapters.http.<adapter_name>` and `adapters.http.opts` instead.
    Feature will be removed in CodeCompanion v18.0.0Total number of cases: 519
    Total number of groups: 75
    
    tests\acp\test_acp.lua: ooooooooooooooooooo
    tests\acp\test_prompt_builder.lua: ooooo
    tests\adapters\acp\test_acp.lua: oooo
    tests\adapters\acp\test_gemini_cli.lua: oo
    tests\adapters\http\copilot\test_copilot.lua: ooooooo
    tests\adapters\http\copilot\test_models.lua: oo
    tests\adapters\http\copilot\test_stats.lua: ooooo
    tests\adapters\http\test_anthropic.lua: oooooooooooooooooooo
    tests\adapters\http\test_deepseek.lua: oooooooooooo
    tests\adapters\http\test_gemini.lua: oooooooo
    tests\adapters\http\test_mistral.lua: oooo
    tests\adapters\http\test_ollama.lua: oooooooooo
    tests\adapters\http\test_openai.lua: ooooooooooo
    tests\adapters\http\test_tools_in_chat_buffer.lua: oooooooooooo
    tests\adapters\http\test_transformers.lua: o
    tests\adapters\test_adapters.lua: ooxxooooooooo
    tests\providers\diff\test_inline.lua: ooooooooooooooooooooooooooo
    tests\providers\diff\test_utils.lua: ooooooooooooooooooooooooooo
    tests\strategies\chat\acp\test_fs.lua: ooooooooooooooo
    tests\strategies\chat\acp\test_handler.lua: oooooooo
    tests\strategies\chat\acp\test_permission_request.lua: ooooooo
    tests\strategies\chat\helpers\test_helpers.lua: oo
    tests\strategies\chat\helpers\test_wait.lua: ooooooooo
    tests\strategies\chat\memory\parsers\test_claude_parser.lua: o
    tests\strategies\chat\memory\parsers\test_parsers.lua: ooo
    tests\strategies\chat\memory\test_memory.lua: ooooxxo
    tests\strategies\chat\slash_commands\test_keymaps.lua: o
    tests\strategies\chat\slash_commands\test_quickfix.lua: oooo
    tests\strategies\chat\slash_commands\test_workspace.lua: oooooooooo
    tests\strategies\chat\test_chat.lua: ooooooxoo
    tests\strategies\chat\test_context.lua: ooooooooxoooooo
    tests\strategies\chat\test_edit_tracker.lua: ooooooooooooooooooooooooo
    tests\strategies\chat\test_messages.lua: o
    tests\strategies\chat\test_settings.lua: o
    tests\strategies\chat\test_subscribers.lua: ooo
    tests\strategies\chat\test_super_diff.lua: ooooooooo
    tests\strategies\chat\test_variables.lua: ooooooooooxo
    tests\strategies\chat\test_watcher.lua: oooooooooooooooo
    tests\strategies\chat\test_workflows.lua: o
    tests\strategies\chat\tools\catalog\helpers\test_patch.lua: oooooooooooooooo
    tests\strategies\chat\tools\catalog\test_cmd_runner.lua: o
    tests\strategies\chat\tools\catalog\test_create_file.lua: o
    tests\strategies\chat\tools\catalog\test_fetch_webpage.lua: o
    tests\strategies\chat\tools\catalog\test_file_search.lua: ooooooooooo
    tests\strategies\chat\tools\catalog\test_grep_search.lua: o
    tests\strategies\chat\tools\catalog\test_insert_edit_into_file.lua: oooo
    tests\strategies\chat\tools\catalog\test_list_code_usages.lua: o
    tests\strategies\chat\tools\catalog\test_next_edit_suggestion.lua: x
    tests\strategies\chat\tools\catalog\test_read_file.lua: oooo
    tests\strategies\chat\tools\catalog\test_search_web.lua: o
    tests\strategies\chat\tools\catalog\test_tool_output.lua: ooooo
    tests\strategies\chat\tools\runtime\test_cmd.lua: oxox
    tests\strategies\chat\tools\runtime\test_queue.lua: xo
    tests\strategies\chat\tools\runtime\test_queue_async.lua: xo
    tests\strategies\chat\tools\runtime\test_runner.lua: oooooooooo
    tests\strategies\chat\tools\runtime\test_user_approval.lua: oooo
    tests\strategies\chat\tools\test_orchestrator.lua: ooo
    tests\strategies\chat\tools\test_tools.lua: ooooooooooooooo
    tests\strategies\chat\tools\test_tool_filter.lua: ooooo
    tests\strategies\chat\ui\test_builder_state.lua: ooo
    tests\strategies\chat\ui\test_fold_reasoning_output.lua: ooo
    tests\strategies\inline\test_inline.lua: oooooooooo
    tests\strategies\inline\test_inline_variables.lua: ooo
    tests\test_cmds.lua: ooooo
    tests\test_extensions.lua: oooooo
    tests\test_has.lua: ooooo
    tests\test_hash.lua: ooo
    tests\test_http.lua: ooooooooo
    tests\test_prompt_library.lua: oxxoo
    tests\test_strategies.lua: oo
    tests\test_symbols.lua: o
    tests\utils\test_buffers.lua: o
    tests\utils\test_context.lua: oooooooooooo
    tests\utils\test_files.lua: oooooooo
    tests\utils\test_ui.lua: ooo
    
    Fails (14) and Notes (0)
    FAIL in tests\adapters\test_adapters.lua | Adapter | can form environment variables:
      Failed expectation for equality.
      Left:  nil
      Right: "HOME"
      Traceback:
        tests\adapters\test_adapters.lua:151
    
    FAIL in tests\adapters\test_adapters.lua | Adapter | can set environment variables in the adapter:
      Failed expectation for equality.
      Left:  {
        content_type = "application/json"
      }
      Right: {
        content_type = "application/json",
        home = "HOME"
      }
      Traceback:
        tests\adapters\test_adapters.lua:169
    
    FAIL in tests\strategies\chat\memory\test_memory.lua | Memory.make() integration: memory is added to a real chat messages stack:
      Failed expectation for equality.
      Left:  "<memory>C:/Users/mspozw/AppData/Local/Temp/nvim.0/TDIr0z/0</memory>"
      Right: "<memory>C:\\Users\\mspozw\\AppData\\Local\\Temp\\nvim.0\\TDIr0z\\0</memory>"
      Traceback:
        tests\strategies\chat\memory\test_memory.lua:220
    
    FAIL in tests\strategies\chat\memory\test_memory.lua | add_files_or_buffers() prevents duplicate files from being added:
      Failed expectation for equality.
      Left:  false
      Right: true
      Traceback:
        tests\strategies\chat\memory\test_memory.lua:283
    
    FAIL in tests\strategies\chat\test_chat.lua | Chat | images are replaced in text and base64 encoded: Error loading lua: [string "<nvim>"]:3: invalid escape sequence near '"What does this [Image](c:'
      Traceback:
        tests\strategies\chat\test_chat.lua:120
    
    FAIL in tests\strategies\chat\test_context.lua | Context | file context_items always have a relative id:
      Failed expectation for string starts with.
    
      Expected string to start with:
      '<attachment filepath="tests/stubs/file.txt">Here is the content from the file'
    
      Observed string:
      <attachment filepath="tests\stubs\file.txt">Here is the content from the file:
    
      ```nil
      Hello World
    
      ```
      </attachment>
      Traceback:
        tests\strategies\chat\test_context.lua:346
    
    FAIL in tests\strategies\chat\test_variables.lua | Variables | :replace | should replace buffer and the buffer name:
      Failed expectation for string starts with.
    
      Expected string to start with:
      "what does file `lua/codecompanion/init.lua`"
    
      Observed string:
      what does file `lua\codecompanion\init.lua` (with buffer number: 53) do?
      Traceback:
        tests\strategies\chat\test_variables.lua:152
    
    FAIL in tests\strategies\chat\tools\catalog\test_next_edit_suggestion.lua | next_edit_suggestion tool:
      Failed expectation for string contains.
    
      Expected string to contain:
      "C:/Users/mspozw/AppData/Local/Temp/svt8.0"
    
      Observed string:
      c:\D\Projects\codecompanion.nvim\[CodeCompanion] 7942063
      Traceback:
        ...ategies\chat\tools\catalog\test_next_edit_suggestion.lua:53
    
    FAIL in tests\strategies\chat\tools\runtime\test_cmd.lua | Tools | cmds | output.errors is called:
      Failed expectation for equality.
      Left:  "Error"
      Right: vim.NIL
      Traceback:
        tests\strategies\chat\tools\runtime\test_cmd.lua:75
    
    FAIL in tests\strategies\chat\tools\runtime\test_cmd.lua | Tools | cmds | can set test flags on the chat object:
      Failed expectation for equality.
      Left:  {
        testing = true
      }
      Right: {}
      Traceback:
        tests\strategies\chat\tools\runtime\test_cmd.lua:117
    
    FAIL in tests\strategies\chat\tools\runtime\test_queue.lua | Tools | queue | can queue functions and commands:
      Failed expectation for equality.
      Left:  "Func[Setup]->Func[Success]->Func[Exit]->Cmd[Setup]->Cmd[Success]->Cmd[Exit]->Func2[Setup]->Func2[Success]->Func2[Exit]"
      Right: "Func[Setup]->Func[Success]->Func[Exit]->Cmd[Setup]->Cmd[Exit]->Func2[Setup]->Func2[Success]->Func2[Exit]"
      Traceback:
        tests\strategies\chat\tools\runtime\test_queue.lua:63
    
    FAIL in tests\strategies\chat\tools\runtime\test_queue_async.lua | Tools | queue | can queue multiple async functions:
      Failed expectation for equality.
      Left:  "AsyncFunc[Setup]->AsyncFunc[Success]->AsyncFunc[Exit]->Cmd[Setup]->Cmd[Success]->Cmd[Exit]->AsyncFunc2[Setup]->AsyncFunc2[Success]->AsyncFunc2[Exit]"
      Right: "AsyncFunc[Setup]->AsyncFunc[Success]->AsyncFunc[Exit]->Cmd[Setup]->Cmd[Exit]->AsyncFunc2[Setup]->AsyncFunc2[Exit]"
      Traceback:
        tests\strategies\chat\tools\runtime\test_queue_async.lua:63
    
    FAIL in tests\test_prompt_library.lua | Prompt Library | can add references:
      Failed expectation for equality.
      Left:  "<file>lua/codecompanion/health.lua</file>"
      Right: "<file>lua\\codecompanion\\health.lua</file>"
      Traceback:
        tests\test_prompt_library.lua:95
    
    FAIL in tests\test_prompt_library.lua | Prompt Library | can add context:
      Failed expectation for equality.
      Left:  "<file>lua/codecompanion/health.lua</file>"
      Right: "<file>lua\\codecompanion\\health.lua</file>"
      Traceback:
        tests\test_prompt_library.lua:181
    

</details>

<details>
<summary>Tests on Windows with this PR</summary>

```
c:\D\Projects\codecompanion.nvim>ver

Microsoft Windows [Version 10.0.22631.5768]

c:\D\Projects\codecompanion.nvim>run_tests
`adapters.<adapter_name>` and `adapters.opts` is deprecated, use `adapters.http.<adapter_name>` and `adapters.http.opts` instead.
Feature will be removed in CodeCompanion v18.0.0Total number of cases: 519
Total number of groups: 75

tests\acp\test_acp.lua: ooooooooooooooooooo
tests\acp\test_prompt_builder.lua: ooooo
tests\adapters\acp\test_acp.lua: oooo
tests\adapters\acp\test_gemini_cli.lua: oo
tests\adapters\http\copilot\test_copilot.lua: ooooooo
tests\adapters\http\copilot\test_models.lua: oo
tests\adapters\http\copilot\test_stats.lua: ooooo
tests\adapters\http\test_anthropic.lua: oooooooooooooooooooo
tests\adapters\http\test_deepseek.lua: oooooooooooo
tests\adapters\http\test_gemini.lua: oooooooo
tests\adapters\http\test_mistral.lua: oooo
tests\adapters\http\test_ollama.lua: oooooooooo
tests\adapters\http\test_openai.lua: ooooooooooo
tests\adapters\http\test_tools_in_chat_buffer.lua: oooooooooooo
tests\adapters\http\test_transformers.lua: o
tests\adapters\test_adapters.lua: ooooooooooooo
tests\providers\diff\test_inline.lua: ooooooooooooooooooooooooooo
tests\providers\diff\test_utils.lua: ooooooooooooooooooooooooooo
tests\strategies\chat\acp\test_fs.lua: ooooooooooooooo
tests\strategies\chat\acp\test_handler.lua: oooooooo
tests\strategies\chat\acp\test_permission_request.lua: ooooooo
tests\strategies\chat\helpers\test_helpers.lua: oo
tests\strategies\chat\helpers\test_wait.lua: ooooooooo
tests\strategies\chat\memory\parsers\test_claude_parser.lua: o
tests\strategies\chat\memory\parsers\test_parsers.lua: ooo
tests\strategies\chat\memory\test_memory.lua: ooooooo
tests\strategies\chat\slash_commands\test_keymaps.lua: o
tests\strategies\chat\slash_commands\test_quickfix.lua: oooo
tests\strategies\chat\slash_commands\test_workspace.lua: oooooooooo
tests\strategies\chat\test_chat.lua: ooooooooo
tests\strategies\chat\test_context.lua: ooooooooooooooo
tests\strategies\chat\test_edit_tracker.lua: ooooooooooooooooooooooooo
tests\strategies\chat\test_messages.lua: o
tests\strategies\chat\test_settings.lua: o
tests\strategies\chat\test_subscribers.lua: ooo
tests\strategies\chat\test_super_diff.lua: ooooooooo
tests\strategies\chat\test_variables.lua: oooooooooooo
tests\strategies\chat\test_watcher.lua: oooooooooooooooo
tests\strategies\chat\test_workflows.lua: o
tests\strategies\chat\tools\catalog\helpers\test_patch.lua: oooooooooooooooo
tests\strategies\chat\tools\catalog\test_cmd_runner.lua: o
tests\strategies\chat\tools\catalog\test_create_file.lua: o
tests\strategies\chat\tools\catalog\test_fetch_webpage.lua: o
tests\strategies\chat\tools\catalog\test_file_search.lua: ooooooooooo
tests\strategies\chat\tools\catalog\test_grep_search.lua: o
tests\strategies\chat\tools\catalog\test_insert_edit_into_file.lua: oooo
tests\strategies\chat\tools\catalog\test_list_code_usages.lua: o
tests\strategies\chat\tools\catalog\test_next_edit_suggestion.lua: o
tests\strategies\chat\tools\catalog\test_read_file.lua: oooo
tests\strategies\chat\tools\catalog\test_search_web.lua: o
tests\strategies\chat\tools\catalog\test_tool_output.lua: ooooo
tests\strategies\chat\tools\runtime\test_cmd.lua: oooo
tests\strategies\chat\tools\runtime\test_queue.lua: oo
tests\strategies\chat\tools\runtime\test_queue_async.lua: oo
tests\strategies\chat\tools\runtime\test_runner.lua: oooooooooo
tests\strategies\chat\tools\runtime\test_user_approval.lua: oooo
tests\strategies\chat\tools\test_orchestrator.lua: ooo
tests\strategies\chat\tools\test_tools.lua: ooooooooooooooo
tests\strategies\chat\tools\test_tool_filter.lua: ooooo
tests\strategies\chat\ui\test_builder_state.lua: ooo
tests\strategies\chat\ui\test_fold_reasoning_output.lua: ooo
tests\strategies\inline\test_inline.lua: oooooooooo
tests\strategies\inline\test_inline_variables.lua: ooo
tests\test_cmds.lua: ooooo
tests\test_extensions.lua: oooooo
tests\test_has.lua: ooooo
tests\test_hash.lua: ooo
tests\test_http.lua: ooooooooo
tests\test_prompt_library.lua: ooooo
tests\test_strategies.lua: oo
tests\test_symbols.lua: o
tests\utils\test_buffers.lua: o
tests\utils\test_context.lua: oooooooooooo
tests\utils\test_files.lua: oooooooo
tests\utils\test_ui.lua: ooo

Fails (0) and Notes (0)

```

</details>

## Checklist

- [x] I've read the [contributing](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [x] I've added [test](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md#testing) coverage for this fix/feature
- [x] I've run `make all` to ensure docs are generated, tests pass and my formatting is applied
- [ ] _(optional)_ I've updated `CodeCompanion.has` in the [init.lua](https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/init.lua#L239) file for my new feature
- [ ] _(optional)_ I've updated the README and/or relevant docs pages

### CODE REVIEW

**Comment by alzwded** [comment]
Hey @olimorris , any interest in this PR?

**Comment by jinzhongjia** [comment]
This pr is very important for windows users

File: tests/strategies/chat/tools/runtime/test_cmd.lua [hunk 1]
```diff
@@ -44,8 +45,10 @@ T["Tools"]["cmds"]["handlers and outputs are called"] = function()
       },
     }
     tools:execute(chat, tool_call)
-    vim.wait(100)
-  ]])
+    vim.wait(%d)
+  ]],
+    vim.fn.has("win32") == 1 and 1000 or 100
```
Comment (olimorris) [inline tests/strategies/chat/tools/runtime/test_cmd.lua]: Instead of repeat this, can we put this a variable at the top of the file?

File: tests/strategies/chat/test_chat.lua [hunk 2]
```diff
@@ -116,7 +116,12 @@ T["Chat"]["prompt decorator is applied prior to sending to the LLM"] = function(
 end
 
 T["Chat"]["images are replaced in text and base64 encoded"] = function()
-  local prompt = string.format("What does this [Image](%s) do?", vim.fn.getcwd() .. "/tests/stubs/logo.png")
+  if vim.fn.executable("base64") == 0 then
```
Comment (olimorris) [inline tests/strategies/chat/test_chat.lua:119]: The latest PR I've merged means we can remove this as we're using Neovim's built in base64 lib

File: tests/strategies/chat/test_context.lua [hunk 3]
```diff
@@ -341,11 +341,14 @@ T["Context"]["file context_items always have a relative id"] = function()
      _G.chat:submit()
    ]])
 
-  h.expect_starts_with(
-    '<attachment filepath="tests/stubs/file.txt">Here is the content from the file',
-    child.lua_get([[_G.chat.messages[#_G.chat.messages].content]])
+  h.expect_match(
+    child.lua_get([[_G.chat.messages[#_G.chat.messages].content]]),
+    [[^<attachment filepath="tests[\\/]stubs[\\/]file.txt">Here is the content from the file]]
```
Comment (olimorris) [inline tests/strategies/chat/test_context.lua:346]: I dislike this on the basis that it overly complicates the assertion. We should have a function that translates this to a windows acceptable string

File: tests/strategies/chat/test_variables.lua [hunk 4]
```diff
@@ -149,7 +149,7 @@ T["Variables"][":replace"]["should replace buffer and the buffer name"] = functi
 
   local message = "what does #{buffer:init.lua} do?"
   local result = vars:replace(message, 0)
-  h.expect_starts_with("what does file `lua/codecompanion/init.lua`", result)
+  h.expect_match(result, "^what does file `lua[\\/]codecompanion[\\/]init.lua`")
```
Comment (olimorris) [inline tests/strategies/chat/test_variables.lua:152]: Let's create a windows test helper to convert a path to a windows acceptable one

File: tests/test_prompt_library.lua [hunk 5]
```diff
@@ -92,8 +92,8 @@ T["Prompt Library"]["can add references"] = function()
   ]])
 
   h.eq(2, #refs)
-  h.eq("<file>lua/codecompanion/health.lua</file>", refs[1].id)
-  h.eq("<file>lua/codecompanion/http.lua</file>", refs[2].id)
+  h.expect_match(refs[1].id, "^<file>lua[\\/]codecompanion[\\/]health.lua</file>$")
```
Comment (olimorris) [inline tests/test_prompt_library.lua:95]: This should use the windows test helper

File: run_tests.cmd
Comment (olimorris) [inline run_tests.cmd:1]: So this file, I do not like. We have the make file and this is a duplication of that and we're now introducing another file to manage and maintain. I would prefer that we include instruction in CONTRIBUTING.md for Windows users telling them how to get the make file working.

**Comment by olimorris** [comment]
Thanks for this. A few comments that would make things a bit cleaner.

**Comment by olimorris** [comment]
And I forgot to say, thank you for all your hard work on this. Really, really appreciate it and opens the plugin up for contributions from many more Windows users.

File: tests/strategies/chat/tools/runtime/test_cmd.lua (hunk 1 above)
Comment (alzwded) [reply tests/strategies/chat/tools/runtime/test_cmd.lua]: Refactored in 1a950bc7191e5a3b1ad837ca8673b92efb75e375

**Comment by alzwded** [comment]
Thanks, I've gone through the comments! But some aren't exactly trivial to fix. I'll ping you back once I sort those out.

File: tests/strategies/chat/test_context.lua (hunk 3 above)
Comment (alzwded) [reply tests/strategies/chat/test_context.lua:346]: I just want to point out my rationale for writing the assert this way: the orientation of the slashes isn't enforced; so if the underlying code decides one day to re-orient the slashes for whatever reason, the test doesn't break.

I'll need to give it a think. Maybe run everything that looks like a path through `vim.fs.normalize()` which does orient the slashes in the *forward* direction.

File: run_tests.cmd
Comment (alzwded) [reply run_tests.cmd:1]: I've added a "Running tests on Native Windows" section, under Testing, in CONTRIBUTING.md. Let me know if it's too wordy.

File: tests/strategies/chat/test_chat.lua (hunk 2 above)
Comment (alzwded) [reply tests/strategies/chat/test_chat.lua:119]: Correct. I've opened a PR for this https://github.com/olimorris/codecompanion.nvim/pull/2341
